version: '3.3'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3001:3001"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - ./data/server_logs:/logs

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "8080:8080"
    volumes:
      - ./data/db:/var/lib/postgresql/data
