name: Workflow CI/CD

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - develop

jobs:
  frontend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 21

    - name: Install Frontend Dependencies
      working-directory: ./frontend
      run: npm install

    - name: Display Node.js version
      working-directory: ./frontend
      run: node -v

    - name: Install Next.js
      working-directory: ./frontend
      run: npm install next

    - name: Build Frontend
      working-directory: ./frontend
      run: npm run build

    - name: Run Frontend Tests
      working-directory: ./frontend
      run: npm test

    - name: Run Frontend Linter
      working-directory: ./frontend
      run: npm run lint

  backend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 21

    - name: Install Backend Dependencies
      working-directory: ./backend
      run: npm install

    - name: Build
      working-directory: ./backend
      run: npm run build
 
    - name: Run Backend Tests
      working-directory: ./backend
      run: npm test

    - name: Run Backend Linter
      working-directory: ./backend
      run: npm run lint
