name: Workflow CI/CD

on:
  push:
  branches:

  pull_request:
    branches:
      - develop

jobs:
  frontend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install Frontend Dependencies
      working-directory: ./frontend
      run: npm install

    - name: Run Frontend Linter
      working-directory: ./frontend
      run: npm run lint

    - name: Build Frontend
      working-directory: ./frontend
      run: npm run build

  backend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install Backend Dependencies
      working-directory: ./backend
      run: npm install

    - name: Run Backend Linter
      working-directory: ./backend
      run: npm run lint

    - name: Build
      working-directory: ./backend
      run: npm run build
 
    - name: Run Backend Tests
      working-directory: ./backend
      run: npm run test
